# https://github.com/lowlighter/metrics
name: Achievement
on:
  schedule: [{cron: "0 11 * * *"}]
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-achievement.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: X
