# https://github.com/lowlighter/metrics
name: Metrics-Languages-Recently
on:
  schedule: [{cron: "0 11 * * *"}]
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: github-languages-metrics-recently.svg
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          plugin_languages_details: lines, percentage
          plugin_languages_sections: recently-used
          plugin_languages_indepth: yes
          delay: 120
