# https://github.com/lowlighter/metrics
name: Metrics-Repo
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-repo-metrics.svg
          config_gemoji: yes
          base: repositories
          repositories: 100
          repositories_forks: no
          repositories_affiliations: owner, collaborator, organization_member
          plugin_lines: yes
