# https://github.com/lowlighter/metrics
name: Metrics-Languages
on:
  schedule: [{cron: "0 11 * * *"}]
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-languages-metrics.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, c, tsql
          plugin_languages_details: lines, percentage
          plugin_languages_threshold: 0.1%
