# https://github.com/lowlighter/metrics
name: Metrics-Projects
on:
  schedule: [{cron: "0 11 * * *"}]
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-projects-metrics.svg
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: tfSheol/crustil/projects/1
          plugin_projects_limit: 4
          plugin_projects_descriptions: yes
