# https://github.com/lowlighter/metrics
name: Metrics-Repo
on:
  schedule: [{cron: "0 11 * * *"}]
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-repo-metrics.svg
          base: repositories
          repositories: 999
          repositories_forks: no
          repositories_affiliations: owner, collaborator
