# https://github.com/lowlighter/metrics
name: Metrics-Languages-Indepth
on:
  schedule: [{cron: "0 11 * * *"}]
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-languages-metrics-indepth.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: html, css, c
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0.01%
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365
