# https://github.com/lowlighter/metrics
name: Metrics-Isocalendar
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-isocalendar-metrics.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
